# Site Settings
baseurl: ""
url: "https://SuJeong2.github.io"

# Blog Settings
theme_settings:
  title: SuJeong2
  favicon: assets/writing.png

  # Profile Settings
  profile:
    image: assets/img/SuJeong2.jpg
    username: SUJEONG LEE
    description: <p>수정쓰의 깃헙 블로그( •̀ ω •́ )y </p> <p>공부하는 것들을 끄적여보자!✍💻 </p>
    experience:
      - start: 2021-01
        end: ing
        experience: 삼성 청년 SW 아카데미(SSAFY) 5기
      - start: 2021-02
        experience: 가천대학교(Gachon University) 졸업
      - start: 2019-06
        end: 2019-11
        experience: 2019 SW 챌린지 공모전 <br>동상, 한국 SW 산업협회장상 수상
      - start: 2019-05
        experience: Ericsson-LG Girls in ICT 2019 해커톤 참가 <br>본선 진출
      - start: 2018-07
        end: 2018-08
        experience: DPSOne 산학 인턴
      - start: 2018-01
        end: 2018-12
        experience: 학부생 연구원 활동
      - start: 2017-03
        end: 2017-06
        experience: 스마트폰 교육 봉사
      - start: 2016-03
        experience: 가천대학교(Gachon University) 입학
    skills:
      - skill: Java
        value: 80 # Percent value
      - skill: Spring
        value: 70 # Percent value

  # Icons
  icons:
    email: "lee.sujeong10111@gmail.com"
    linkedin: # Full URL
    github: SuJeong2
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: sue_jjng
    blog: sj971020
    portfolio: portfolio

  # Disqus
  disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
